# Generated by Django 3.1.4 on 2020-12-18 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60)),
                ('catch_phrase', models.CharField(max_length=60)),
            ],
        ),
    ]
